@startuml
folder blockchain {
  folder utils {
      artifact collection
        note bottom
          Collection helper functions.
          (for bit array at the moment)
        end note
      artifact crypto
        note bottom
          Cryptographic helper functions.
          (for the Schnorr's multi-signature)
        end note
      artifact network
        note bottom
          Network elements.
          (for network peers, DS Committee, etc)
        end note
  }
  folder zilliqa {
      artifact block
        note bottom
          TX-Block helper functions.
        end note
      artifact node
        note bottom
          Node helper functions.
        end note
  }
}
@enduml
